### ISSUE TITLE
FInding functions and operators for Subtypes of classes

### ISSUE THREAD

**Issue by Jozott00** [flofriday/Moose#18]
So 
```
a(A())

func a(a: B) {}
class A < B{}
class B{}
```
fails at the moment, as well as
```
++A()

prefix ++ (a: B) {}
class A < B{}
class B{}
```

**Comment by flofriday** [comment]
Oh no, can you also post the Error?

And are those already tests? If not we schould add them.

**Comment by Jozott00** [comment]
Yes these are already tests. The issue is more like a reminder for me to implement it ^^ we have to add it to the rate function in the typescope. Right now only builtin types are considered
