### ISSUE TITLE
Support of escape characters

### ISSUE THREAD

**Issue by Jozott00** [flofriday/Moose#34]
We have to support escape characters like `\n`, `\t` or `\r`.
Right now they don't get parsed. I don't know if it is possible to let swift handle this for all strings by default...

**Comment by flofriday** [comment]
Sure if swift can handle these that would be nice. This feature too is nice to have but not strictly necessary and we should focus first on making the language correct first with our core features.

**Comment by flofriday** [comment]
But if we implement this it would also be lovley if we could have string interpolation like swift 😍

**Comment by Jozott00** [comment]
Yes, but it is quite difficult to built a solid cli program without`\n` haha (for the showcase demo example)

**Comment by flofriday** [comment]
true yeah we should handle that, also it would be nice to have a print without the newline.

**Comment by Jozott00** [comment]
yes, probably just differ between println and print is the easiest way

**Comment by Jozott00** [comment]
implemented
