### ISSUE TITLE
Support of dynamic type casting

### ISSUE THREAD

**Issue by Jozott00** [flofriday/Moose#35]
We need dynamic type casting. 

```dart 
a: B = A()
b: A = a

class A < B {}
class B {}
```

Of course throws the Error:
```
-- CompileError ----------------------------------------------------------------

  5| b: A = a
     ^^^^^^^^

`B` does not extend declared type `A`.
```

But right know we have no possibility to use the dynamic type A of the variable a.

**Comment by flofriday** [comment]
The error we get is correct and I don't think we should allow the example above.

Dynamic cast would be nice but I don't think it is necessary for a MVP of a language. I think we should first focus on more pressing issues ;)

**Comment by Jozott00** [comment]
Yes the error is perfectly fine

haha ok lets talk about it later

**Comment by flofriday** [comment]
I'm going to close this since we decided that for now we won't implement it for now.
