### ISSUE TITLE
Constructor of BuiltIn Types is valid

### ISSUE THREAD

**Issue by Jozott00** [flofriday/Moose#7]
Currently one could initialize built in types like `Int()`. This is not checked in typechecker.

**Comment by flofriday** [comment]
That is true, however I don't quite get it because it will fail in the environment. The Scope and Environment are quite similar so why is it in the scope but not in the environment?

**Comment by Jozott00** [comment]
This is fixed now. Before calling a constructor we now check if it is a builtin type
